### ISSUE TITLE
Support on Google Cloud when cloud shell is diabled.

### ISSUE THREAD

**Issue by Liaomessi** [google-marketing-solutions/ads-policy-monitor#30]
Hi team, I try to use this tool on google cloud following the readme.
But my google cloud shell has been disabled by G Suite admin. 
If the cloud shell can not be used, is there any other way to deploy this tool to google cloud?
![image](https://github.com/google-marketing-solutions/ads-policy-monitor/assets/42334988/58c769b5-72fe-4e8e-b003-8376f6d1ae32)

**Comment by tdsymonds** [comment]
You should also be able to run this from a local machine provided you have [Terraform installed](https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli) and [the Google Cloud CLI](https://cloud.google.com/sdk/docs/install).

The deployment instructions should be the same, the only difference is you need to run `gcloud init` to configure the gcloud cli instead of the `gcloud config set project` command.
